package:
  name: sams-dev
  version: 0.0.0

source:
  path: ../../

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - python
    - setuptools
    - numpy
    - scipy
    - pymbar
    - openmm >=7.1.0
    - parmed
    - openmoltools
    - alchemy
    - openmmtools

  run:
    - python
    - setuptools
    - numpy
    - scipy
    - pymbar
    - openmm >=7.1.0
    - parmed
    - openmoltools
    - alchemy
    - openmmtools

test:
  requires:
    - nose
    - nose-timer
  imports:
    - sams


about:
  home: https://github.com/choderalab/perses
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
