package:
  name: sams-dev
  version: 0.0.0

source:
  path: ../../

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - python
    - setuptools
    - numpy
    - scipy
    - pymbar
    - openmm >=7.1.0
    - netcdf4
    - parmed
    - openmoltools
    - alchemy >=1.2.1
    - openmmtools
    - matplotlib
    - seaborn
    - mdtraj

  run:
    - python
    - setuptools
    - numpy
    - scipy
    - pymbar
    - openmm >=7.1.0
    - netcdf4
    - parmed
    - openmoltools
    - alchemy >=1.2.1
    - openmmtools
    - matplotlib
    - seaborn
    - mdtraj

test:
  requires:
    - nose
    - nose-timer
  imports:
    - sams

about:
  home: https://github.com/choderalab/sams
  license: MIT
  license_file: LICENSE
  summary: Self-adjusted mixture sampling toolkit for molecular simulations
